Revert "Implement EGL API for MESA_query_driver"
This reverts commit 5efc49c664b5d08c63b67233ddec5d70ab1ad4da.

with default warnings configuration, this commit generates:

   ../src/egl/main/eglapi.c:2654:1: error: no previous prototype for
            ‘eglGetDisplayDriverConfig’ [-Werror=missing-prototypes]