android: util: Add libcutils to Android.mk shared libs
Otherwise:

    external/mesa3d/src/util/os_misc.c:59:12: fatal error: 'cutils/properties.h' file not found
    #  include <cutils/properties.h>
               ^~~~~~~~~~~~~~~~~~~~~

And:

    ld.lld: error: undefined symbol: property_get
    >>> referenced by os_misc.c:193 (external/mesa3d/src/util/os_misc.c:193)
    >>>               os_misc.o:(os_get_option) in archive out/target/product/discovery/obj/STATIC_LIBRARIES/libmesa_util_intermediates/libmesa_util.a

Fixes: 7f851fdd580 ("util: Add property_get() fallback for android")
Acked-by: Rob Clark <robclark@freedesktop.org>
Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/7861>