Revert "glsl: reject image qualifiers with non-image types inside uniform blocks"
This reverts commit f58a9c5afa572eee155fc281fbb6fc5b763871a3.

This causes lots of ES 3.1 CTS tests to fail to compile a bit of code
like:

   layout(binding = 0) buffer InOut
   {
        highp uint inputValues[384];
        highp uint outputValues[384];
        coherent highp uint groupValues[64];      <-----
   } sb_inout;

   error: memory qualifiers may only be applied to images