r600g: Fix Clang return-type build error.
Fix Clang return-type error introduced with commit
4fd30ea2bf235677e8e001536d5b115ea8eb4c9e "gallium: make
pipe_context::begin_query return a boolean".

  CC       r600_query.lo
r600_query.c:443:3: error: non-void function 'r600_begin_query' should return a value [-Wreturn-type]
                return;
                ^

Signed-off-by: Vinson Lee <vlee@freedesktop.org>
Reviewed-by: Tom Stellard <thomas.stellard@amd.com>