configure.ac: require libdrm 2.4.66 for drmGetDevice
since 4b979ce6cda877ba52ddcff4be8845fd6adc5ad7
src/gallium/winsys/amdgpu/drm/amdgpu_winsys.c no longer compiles:
error: unknown type name ‘drmDevicePtr’