progs: Comment out gallium/raw/SConscript from progs/SConscript.
Commit 8f3c4a1c717c31ec3fcac9d64655ef2df867d35e broke the default SCons
build.
NameError: name 'graw' is not defined:

This patch allows the default SCons build to work again until a proper
fix is available.