util: Fix unmatched parenthesis.
Fixes MSVC build error introduced with commit
d1ac908739332c109aed665a6cc1a09b670ac4b3.

src\gallium\auxiliary\util\u_cpu_detect.c(286) : fatal error C1012: unmatched parenthesis : missing '('

Signed-off-by: Vinson Lee <vlee@freedesktop.org>