mesa/sso: Fix typo of 'unsigned'.
Fix build error introduced with commit 1a5c00be3a83a4954b58147da9a3a14e2b612308.

  CC       pixeltransfer.lo
main/pipelineobj.c: In function '_mesa_delete_pipeline_object':
main/pipelineobj.c:59:4: error: unknown type name 'unsinged'
    unsinged i;
    ^

Signed-off-by: Vinson Lee <vlee@freedesktop.org>