gallium/radeon: fix missing winsys include in pipe-loader.
The commit a6bb25e4d476555b139e588328e4603c895218f5 introduced a build
error:

error: dereferencing pointer to incomplete type

This patch fixes this issue in all the affected files.

Reviewed-by: Tom Stellard <thomas.stellard@amd.com>